name: "Run on Yarn"
description: "Composite GitHub Action to run a command with Yarn."
inputs:
  command:
    description: "Command to run"
    required: true
  node-version:
    description: "Node Version"
    default: 14
    required: false
  github-token:
    description: "Github token to use when checking out the repo"
    default: ${{ github.token }}
    required: false
  fetch-depth:
    description: "Checkout depth"
    default: 1
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - uses: actions/setup-node@v2
      with:
        cache: "yarn"
        node-version: "${{ inputs.node-version }}"
    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-yarn-node-${{ inputs.node-version }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies If Not Cached
      run: \[ -d node_modules \] || yarn install --frozen-lockfile
      shell: bash
    - run: yarn ${{ inputs.command }}
      shell: bash
