name: 'Run on Yarn'
description: 'Composite GitHub Action to run a command with Yarn.'
inputs:
  command:
    description: 'Command to run'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: 'yarn'
        node-version: '14'
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-node-14-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies If Not Cached
      run: \[ -d node_modules \] || yarn install --frozen-lockfile
      shell: bash
    - run: yarn ${{ inputs.command }}
      shell: bash
